name: phpstan-analysis
on:
  push:
    branches:
      - master

jobs:
  build-and-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1.10"

      - name: Install dependencies
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan static code analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon
    
  build-app:
    needs: build-and-code-review
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: loicdi/website:push-on-master

  deploy-project:
    needs: build-app
    runs-on: ubuntu-latest

    steps:
      - name: Deploy project
        run: echo "Deploy project"

      - name: Pull Docker image
        run: docker pull loicdi/website:push-on-master

      - name: Launch Docker container
        run: |
          docker run -d -p 8082:80 --name push-on-master loicdi/website:push-on-master